// packages/solid/src/radio/radio.tsx
import { createEffect, createMemo, createReaction, createSignal, on, onMount, splitProps, type Component, type Ref } from "solid-js";
import { Ripple } from "../ripple";
import { styles } from "./radio.css";
import { FocusRing } from "../focus";

export namespace Radio {
  export type Props =
  & {}
  & {
    ref?: Ref<Element>;
    value: Value;
    groupValue: Value;
    onChange?: (value: Value) => void;
  }

  export type Value = string | number | symbol;

  export interface Element extends HTMLElement {}
}

export const Radio: Component<Radio.Props> = (props) => {
  const [local, others] = splitProps(props, ["ref", "onChange", "value", "groupValue"]);

  let ref!: HTMLElement;

  const checked = createMemo(() => local.value === local.groupValue);

  const [animate, setAnimate] = createSignal(false);

  const track = createReaction(() => setAnimate(true));
  track(() => local.groupValue);


  return (
    <div
      ref={ref as HTMLDivElement}
      class={styles.container({ checked: checked() })}
      role="radio"
      onClick={() => local.onChange?.(local.value)}
      tabIndex={0}>
        <Ripple for={ref} />
        <FocusRing for={ref} />
        <div
          class={styles.icon({
            checked: checked(),
            animate: animate(),
            disabled: false,
          })} />
    </div>
  );
}

// packages/react/src/radio/radio.tsx
import { Ripple } from "../ripple";
import { styles } from "./radio.css";
import { FocusRing } from "../focus";
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState } from "react";

export namespace Radio {
  export type Props =
    & {
      value: Value;
      groupValue: Value;
      onChange?: (value: Value) => void;
    };

  export type Value = string | number | symbol;

  export interface Element extends HTMLElement {}
}

export const Radio = forwardRef<Radio.Element, Radio.Props>(
  (
    {
      groupValue,
      value,
      onChange,
    },
    forwardedRef,
  ) => {
    const ref = useRef<HTMLDivElement>(null);
    useImperativeHandle(
      forwardedRef,
      ()  => ref.current!,
      [],
    );

    const checked = useMemo(() => value === groupValue, [value, groupValue]);

    const render = useRef(0);
    const [animate, setAnimate] = useState(false);

    useEffect(
      () => {
        if(render.current < 2) render.current++;
        else if(!animate) setAnimate(true);
      },
      [checked],
    );


    return (
      <div
        ref={ref}
        className={styles.container({ checked })}
        role="radio"
        onClick={() => onChange?.(value)}
        tabIndex={0}>
          <Ripple for={ref} />
          <FocusRing for={ref} />
          <div
            className={styles.icon({
              checked,
              animate,
              disabled: false,
            })} />
      </div>
    );
  },
);
