// packages/solid/src/native/modal.tsx
import { createEffect, mergeProps, on, splitProps, type FlowComponent, type JSX, type Ref } from "solid-js";
import { Dynamic, Portal, Show, spread } from "solid-js/web";
import { mergeRefs } from "@solid-primitives/refs";
import { clsx } from "clsx/lite";

import { styles } from "./modal.css";

export namespace Modal {
  export type Props =
    & Omit<
      JSX.HTMLAttributes<HTMLElement>,
      "ref" | "children"
    >
    & {
      ref?: Ref<Element>;
      open: boolean;
      onOpenChange?: (value: boolean) => void;
      children: JSX.Element;
    };
  export interface Element extends HTMLElement {}
}

const PortalModal: FlowComponent<Modal.Props> = (props) => {
  const mergedProps = mergeProps(
    { open: false },
    props,
  );
  const [local, others] = splitProps(
    mergedProps,
    ["ref", "class", "open", "onOpenChange", "children"],
  );

  let ref!: HTMLElement;

  createEffect(() => {
    const className = clsx(styles.portal, local.class);
    ref.classList.add(className);
    spread(ref, others, false, true);
  });

  return (
    <Show when={props.open}>
      <Portal
        ref={mergeRefs(element => ref = element, local.ref)}
        mount={document.body}>
          {local.children}
      </Portal>
    </Show>
  )
}

const NativeModal: FlowComponent<Modal.Props> = (props) => {
  const mergedProps = mergeProps(
    { open: false },
    props,
  );
  const [local, others] = splitProps(
    mergedProps,
    ["ref", "class", "open", "onOpenChange", "children"],
  );
  let ref!: HTMLDialogElement;

  createEffect(on(
    () => local.open,
    (open) => {
      if(open) {
        ref.showModal();
      } else {
        ref.close();
      }
    }
  ));

  const onCancel: JSX.EventHandler<HTMLDialogElement, Event> = (event) => {
    event.preventDefault();
    local.onOpenChange?.(false);
  }

  return (
    <dialog
      ref={mergeRefs(
        element => ref = element as HTMLDialogElement,
        local.ref
      )}
      class={
        clsx(styles.native, local.class)
      }
      onCancel={onCancel}
      {...others}>
        {local.children}
    </dialog>
  )
}


const SUPPORTS_NATIVE =
  "HTMLDialogElement" in window &&
  typeof HTMLDialogElement === "function";

export const Modal = SUPPORTS_NATIVE ? NativeModal : PortalModal;

// packages/react/src/modal/modal.tsx
import { createContext, forwardRef, useContext, useEffect, useImperativeHandle, useRef, type FC, type ForwardedRef, type HTMLAttributes, type ReactNode } from "react"
import { createPortal } from "react-dom";
import clsx from "clsx/lite";
import { styles } from "./modal.css";

export namespace Modal {
  export type Props =
    & Omit<
      HTMLAttributes<HTMLElement>,
      "children"
    >
    & {
      open?: boolean;
      onCancel?: () => void;
      children?: ReactNode;
    };

  export interface Element extends HTMLElement {}
}

type InternalModalContextData = {
  isOpen: boolean;
  close: () => void;
}

const InternalModalContext = createContext<InternalModalContextData | undefined>(undefined);
const useInternalModalContext = () => useContext(InternalModalContext);

const NativeModal = forwardRef<Modal.Element, Modal.Props>(
  (
    {
      className,
      open = false,
      onCancel,
      children,
      ...rest
    },
    forwardedRef,
  ) => {
    const ref = useRef<HTMLDialogElement>(null);
    useImperativeHandle(
      forwardedRef,
      () => ref.current!,
      [],
    );

    useEffect(
      () => {
        if(!ref.current) return;
        if(open) {
          ref.current.showModal();
        } else {
          ref.current.close();
        }
      },
      [open],
    );
    const context: InternalModalContextData = {
      isOpen: open,
      close: () => onCancel?.(),
    };

    return (
      <dialog
        ref={ref}
        className={clsx(className, styles.native)}
        onCancel={
          onCancel
            ? (event) => {
              event.preventDefault();
              onCancel();
            }
            : undefined
        }
        {...rest}>
          <InternalModalContext.Provider
            value={context}
            children={children} />
      </dialog>
    );
  }
);

const PortalModal = forwardRef<Modal.Element, Modal.Props>(
  (
    {
      className,
      open = false,
      onCancel,
      children,
      ...rest
    },
    forwardedRef
  ) => {
    const ref = useRef<HTMLDivElement>(null);
    useImperativeHandle(
      forwardedRef,
      () => ref.current!,
      [],
    );

    const context: InternalModalContextData = {
      isOpen: open,
      close: () => onCancel?.(),
    };

    return createPortal(
      open && (
        <div
          ref={ref}
          className={clsx(className, styles.portal)}
          {...rest}>
            <InternalModalContext.Provider
              value={context}
              children={children} />
        </div>
      ),
      document.body,
    );
  },
);


export namespace Modal {
  export namespace Backdrop {
    export type Props =
      & Omit<
        HTMLAttributes<HTMLElement>,
        "children"
      >
      & {

      };

    export interface Element extends HTMLElement {}
  }
}

const Backdrop = forwardRef<Modal.Backdrop.Element, Modal.Backdrop.Props>(
  (
    {
      className,
      ...rest
    },
    forwardedRef,
  ) => {
    const { isOpen, close } = useInternalModalContext()!;

    return (
      <div
        ref={forwardedRef as ForwardedRef<HTMLDivElement>}
        className={clsx(
          styles.backdrop({}),
          className,
        )}
        onClick={close}
        {...rest} />
    );
  }
)
const SUPPORTS_NATIVE =
  "HTMLDialogElement" in window &&
  typeof HTMLDialogElement === "function";

export const Modal = Object.assign(
  SUPPORTS_NATIVE ? NativeModal : PortalModal,
  { Backdrop },
);
