// packages/react/src/button/button.tsx
import { forwardRef, useImperativeHandle, useRef, type ButtonHTMLAttributes, type ReactNode } from "react";
import { FocusRing } from "../focus";
import { Ripple } from "../ripple";
import clsx from "clsx";
import { styles } from "./button.css";

export namespace Button {
  export type Variant = "elevated" | "filled" | "filledTonal" | "outlined" | "text";
  export type Props =
    & Omit<
      ButtonHTMLAttributes<HTMLButtonElement>,
      "children"
    >
    & {
      variant: Variant;
      icon?: ReactNode;
      label: ReactNode;
    };
  export interface Element extends HTMLButtonElement {}
}

export const Button = forwardRef<Button.Element, Button.Props>(
  (
    {
      className,
      disabled,
      variant,
      icon,
      label,
      ...rest
    },
    forwardedRef,
  ) => {
    const ref = useRef<HTMLButtonElement>(null);
    useImperativeHandle(
      forwardedRef,
      () => ref.current!,
      [],
    );

    return (
      <button
        ref={ref}
        className={clsx(
          styles.container({
            variant,
          }),
          className,
        )}
        disabled={disabled}
        {...rest}>
          <Ripple for={ref} disabled={disabled} />
          <FocusRing for={ref} />
          {variant === "outlined" && (
            <div className={
              styles.outline({})
            } />
          )}
          {icon && (
            <div>
              {icon}
            </div>
          )}
          <span>{label}</span>
      </button>
    )
  },
);

// packages/solid/src/button/button.tsx
import { Show, splitProps, type Component, type JSX, type Ref } from "solid-js";
import { FocusRing } from "../focus";
import clsx from "clsx/lite";
import { styles } from "./button.css";
import { Ripple } from "../ripple";
import { MaterialSymbol } from "../icon-old";

export namespace Button {
  export type Props = PublicProps & ProtectedProps;
  export type ProtectedProps = {
    background?: JSX.Element;
    overlay?: JSX.Element;
  }
  export type PublicProps =
    & Omit<
      JSX.ButtonHTMLAttributes<HTMLButtonElement>,
      "ref" | "children"
    >
    & {
      ref?: Ref<Element>;
      icon?: JSX.Element;
      label: JSX.Element;
    };

  export interface Element extends HTMLElement {}



  export namespace Background {
    export type Props = JSX.HTMLAttributes<HTMLElement>;
  }
}

export const Button: Component<Button.Props> = (props) => {
  const [local, others] = splitProps(
    props,
    ["ref", "class", "background", "overlay", "icon", "label"],
  );

  let ref!: HTMLElement;

  const icon = (
    <Show when={local.icon}>{
      (icon) => (
        <MaterialSymbol.Slot class={styles.icon}>
          {icon()}
        </MaterialSymbol.Slot>
      )
    }</Show>
  );

  return (
    <div
      ref={ref as HTMLDivElement}
      class={clsx(
        styles.container({
          hasIcon: !!local.icon,
        }),
        local.class,
      )}>
      {local.overlay}
      <div class={
        styles.background()
      } />
      <Ripple for={ref} />
      <FocusRing for={ref} />
      <button class={styles.control()}>
        <div class={styles.touchTarget()} />
        {icon}
        <span>
          {local.label}
        </span>
      </button>
    </div>
  );
}
