// examples/react/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { App } from "./app";

import "@fontsource-variable/material-symbols-rounded/full.css";
import "@fontsource-variable/open-sans";
import "@fontsource-variable/raleway";

import "~/styles/theme.css";
import "~/styles/reset.css";


createRoot(
  document.getElementById("root")!,
).render(
  <StrictMode>
    <App />
  </StrictMode>,
)

// examples/solid/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import { App } from "./app";

import "@fontsource-variable/material-symbols-rounded/full.css";
import "@fontsource-variable/open-sans";
import "@fontsource-variable/raleway";

import "~/styles/theme.css";
import "~/styles/reset.css";

render(
  () => <App />,
  document.getElementById("root")!,
);
