// packages/solid/src/tabs/tab.tsx
import { type JSX, type Ref, type Component, splitProps } from "solid-js";
import clsx from "clsx/lite";
import { styles } from "./tab.css";
import { mergeRefs } from "@solid-primitives/refs";
import { Ripple } from "../ripple";
import { FocusRing } from "../focus";

export namespace Tab {
  export type Props =
  & Omit<
    JSX.ButtonHTMLAttributes<HTMLButtonElement>,
    "ref" | "role" | "aria-selected" | "children"
  >
  & {
    ref?: Ref<Element>;
    selected?: boolean;
    icon?: JSX.Element;
    label: JSX.Element;
    indicator?: JSX.Element;
  }

  export interface Element extends HTMLButtonElement {}
}
export const Tab: Component<Tab.Props> = (props) => {
  const [local, others] = splitProps(
    props,
    ["ref", "class", "selected", "icon", "label", "indicator"]
  );

  let ref!: HTMLButtonElement;

  return (
    <button
      ref={mergeRefs(element => ref = element, local.ref)}
      role="tab"
      class={clsx(
        styles.container({
          selected: local.selected ?? false,
        }),
        local.class,
      )}
      aria-selected={local.selected}
      {...others}>

        {local.indicator}
        <Ripple for={ref} class={styles.stateLayer({ selected: local.selected ?? false })} />
        <FocusRing for={ref} />
        <span class={styles.content({
          selected: local.selected ?? false,
        })}>
          {local.icon}
          {local.label}
        </span>
    </button>
  );
}

// packages/react/src/tabs/tab.tsx
import { createIdentifiableElement, type ComposableForwardRefExoticComponent, type ForwardRefExoticComponentProps } from "@star4/react-utils";
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, type ButtonHTMLAttributes, type ReactNode } from "react";
import clsx from "clsx/lite";
import { Ripple } from "../ripple";
import { FocusRing } from "../focus";
import { useInternalTabBarContext, type TabBar } from "./tab-bar";
import { styles } from "./tab.css";

export namespace Tab {
  export type Props<T extends Value> =
    & Omit<
      ButtonHTMLAttributes<HTMLButtonElement>,
      "role" | "children"
    >
    & {
      value: T;
      icon?: ReactNode;
      label: ReactNode;
    };
  export type PropsWithRef<T extends Value> = ForwardRefExoticComponentProps<Tab.Element, Tab.Props<T>>;
  export type Value = TabBar.Value;
  export interface Element extends HTMLButtonElement {}
}
const TabComponent = forwardRef<Tab.Element, Tab.Props<Tab.Value>>(
  function Tab(
    {
      className,
      onClick,
      value,
      icon,
      label,
      ...rest
    },
    forwardedRef,
  ) {
    const { isSelected, setSelected } = useInternalTabBarContext();


    const ref = useRef<HTMLButtonElement>(null);
    useImperativeHandle(
      forwardedRef,
      () => ref.current!,
      [],
    );

    const selected = useMemo(() => isSelected(value), [value, isSelected]);


    useEffect(
      () => {

      },
      [],
    );

    return (
      <button
        ref={ref}
        className={clsx(
          styles.container({ selected }),
          className
        )}
        role="tab"
        onClick={(event) => {
          setSelected(value);
          onClick?.(event);
        }}
        {...rest}>
          <Ripple for={ref} className={styles.stateLayer} />
          <FocusRing for={ref} />
          <span className={styles.content({ selected })}>
            {icon}
            {label}
          </span>
      </button>
    )
  },
) as ComposableForwardRefExoticComponent<
  Tab.PropsWithRef<Tab.Value>,
  <T extends Tab.Value>(props: Tab.PropsWithRef<T>) => ReactNode
>;

export const Tab = Object.assign(
  TabComponent,
  createIdentifiableElement<Tab.Props<Tab.Value>>("IS_TAB"),
);
