// packages/solid/src/dialog/dialog.tsx
import { createSignal, type Component, type JSX, type Ref } from "solid-js";
import { createPresence } from "@solid-primitives/presence";
import { Modal } from "../native";
// import { makePromise } from "../utils";
import { styles } from "./dialog.css";

export namespace Dialog {
  export type Props = {
    ref?: Ref<Element>;
    open: boolean;

    headline?: JSX.Element;
    actions?: JSX.Element;
  }

  export interface Element {
    modal: JSX.Element;
    container: JSX.Element;
  }
}

export const Dialog: Component<Dialog.Props> = (props) => {
  const [open, setOpen] = createSignal(false);
  const {
    isMounted,
    isEntering,
    isExiting,
    isAnimating,
  } = createPresence(open, {
    enterDuration: 500,
    exitDuration: 150,
  });

  return (
    <>
      <button onClick={() => setOpen(true)}>Open</button>
      <Modal open={isMounted()} onOpenChange={setOpen} class={styles.modal()}>
        <div
          class={styles.container({
            entering: isEntering(),
            exiting: isExiting(),
          })}>

            <div class={styles.headline()}>
              <h2>{props.headline}</h2>
            </div>

            <div class={styles.actions()}>
              <button onClick={() => setOpen(false)}>Close</button>

            </div>
        </div>
      </Modal>
    </>
  );
}

// packages/react/src/dialog/dialog.tsx
import { useEffect, type FC, type ReactNode } from "react";
import { Modal } from "../modal"
import { usePresence } from "../utils";
import clsx from "clsx";
import { styles } from "./dialog.css";
import { Divider } from "../divider";

export namespace Dialog {
  export type Props = {
    open?: boolean;
    onCancel?: () => void;

    icon?: ReactNode;
    headline?: ReactNode;
    content?: ReactNode;
    actions?: ReactNode;
  }
}

export const Dialog: FC<Dialog.Props> = ({
  open = false,
  onCancel,
  icon,
  headline,
  content,
  actions,
}) => {
  const {
    isMounted,
    isEntering: entering,
    isExiting: exiting,
    // isVisible,
    // isAnimating,
  } = usePresence({
    source: open,
    transitionDuration: [500, 150],
  });

  return (
    <Modal open={isMounted} onCancel={onCancel} className={styles.modal()}>
      <Modal.Backdrop className={styles.scrim({ entering, exiting })} />
      <div
        className={
          styles.container({ entering, exiting })
        }
        role="dialog">
          <div className={styles.headline({ entering, exiting })}>
            {icon && (
              <div className={styles.icon}>{icon}</div>
            )}
            {headline && (
              <h2 className={styles.headlineText}>{headline}</h2>
            )}
            {/* <Divider /> */}
          </div>
          <div className={styles.content({ entering, exiting })}>
            {content}
          </div>
          {actions && (
            <div className={styles.actions({ entering, exiting })}>
              {/* <Divider /> */}
              {actions}
            </div>
          )}
      </div>
    </Modal>
  )
}
